### ISSUE TITLE
[FEATURE] ADD WORKFLOW COMMAND

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/machineshop#187]
command should read a profile like the following and be able to
* render templates to files and commit to branch
* read github prs (labels - label identifies status of workflow) 
* change github lables (for post action)

```yaml
---
workflow:
  - name: terraform
    description: "Terraform apply"
    matchLables:
      - terraform 
      - apply
    render:
      - name: ansibleConfig.yaml
        file: |
          playbook: sthings.baseos.setup
          inventory: {{ ansibleInventory }}
    postScript:
      - var: ansibleInventory
        script: |
          terraform apply -auto-approve
    reLable:
      - ansible
      - baseos
 ```

**Comment by patrick-hermann-sva** [comment]
```yaml
---
workflow:
  - name: terraform
    description: "Ansible inventory"
    matchLables:
      - terraform 
      - apply
    run:
      - tfinventory
    runVars:
       - inventoryPath=inventory.yaml
    add:
       - inventory.yaml:inventory.yaml
    reLable:
      - ansible
      - baseos
```
