### ISSUE TITLE
[FEATURE] - ADD DYNAMIC RENDERING OF HEADER

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/machineShop#3]

**Comment by patrick-hermann-sva** [comment]
add 

```
task: git-push
gh pr create 
```

in Taskfile

**Comment by patrick-hermann-sva** [comment]
```
  pr:
    desc: Opens a pull request using gh
    deps:
      - lint
    cmds:
      - gh pr create
    interactive: true
```
