### ISSUE TITLE
[FEATURE] - ADD NON SUDO INSTALL OPTION (e.g GO MODULES) 

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/machineShop#30]
go modules installation not working w/ go modules

```yaml
script:
  - age:
      script: |
        go install filippo.io/age/cmd/...@v1.1.1
```

```bash
 sh /tmp/machineShop/age.sh
sh: 0: cannot open /tmp/machineShop/age.sh: Permission denied
```
