### ISSUE TITLE
[FEATURE] - ADD RENDERING OF BINARY NAME

### ISSUE THREAD

**Issue by patrick-hermann-sva** [stuttgart-things/machineShop#31]
```yaml
---
binary:
  - age:
      url: https://github.com/FiloSottile/age/releases/download/v1.1.1/age-v1.1.1-linux-amd64.tar.gz
      bin: sops-v3.8.1.linux.amd64
```
